version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
